---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_

:release_build:
 :output: smartline.hex
 :use_assembly: FALSE

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :include:
    - "#{ENV['XC16PATH']}/support/PIC24E/h"
    - "#{ENV['XC16PATH']}/support/generic/h"
    - "#{ENV['XC16PATH']}/include/lega-c"

:defines:
  :commmon: &common_defines
    - UNITY_INT_WIDTH=16
    - CMOCK_MEM_INDEX_TYPE=uint16_t
    - CMOCK_MEM_PTR_AS_INT=uint16_t
    - CMOCK_MEM_ALIGN=1
    - CMOCK_MEM_SIZE=4096
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools:
  :test_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24EP128GP204
      - -x c
      - -omf=elf
      - -msmart-io=1
      - -msfr-warn=off
      - -legacy-libc
      - -c
      - "${1}"
      - -o "${2}"
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -Wall
      - -mlarge-code
      - -mlarge-data
      - -mlarge-scalar
      - -mconst-in-data
  :test_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24EP128GP204
      - -legacy-libc
      - ${1}
      - -o "./build/release/TestBuild.out"
      - -Wl,-Tp24EP128GP204.gld,--heap=1024,--stack=16,--local-stack,--no-check-sections,--data-init,--pack-data,--handles,--isr,--no-gc-sections,--fill-upper=0,--stackguard=16,--no-force-link,--smart-io,-Map=./build/release/TestOutput.map,--report-mem
  :test_fixture:
    :executable: ruby
    :name: "Microchip simulator test fixture"
    :stderr_redirect: :win #inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/simulation/sim_test_fixture.rb
  :release_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24EP128GP204
      - -x c
      - -omf=hex
      - -msmart-io=1
      - -msfr-warn=off
      - -legacy-libc
      - -c
      - "${1}"
      - -o "${2}"
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      - -mlarge-code
      - -mlarge-data
      - -mlarge-scalar
      - -mconst-in-data
  :release_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=24EP128GP204
      - -legacy-libc
      - ${1}
      - -o "${2}"
      - -Wl,-Tp24EP128GP204.gld,--stack=16,--local-stack,--no-check-sections,--data-init,--pack-data,--handles,--isr,--no-gc-sections,--fill-upper=0,--stackguard=16,--no-force-link,--smart-io,-Map=./build/release/ReleaseOutput.map,--report-mem

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...
